title: ai.xebia.ms
email: microsoft@xebia.com
description: >-
  Your first stop for all things AI at Microsoft. Use our resources to learn about AI, find the right tools, and get help with your AI projects or stay updated on the latest trends.
url: "https://ai.xebia.ms"
twitter_username: xebia
github_username:  xebia
linkedin_username: xebia
show_excerpts: true
author: Xebia Microsoft Services

google_analytics: TODO

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap